#! /bin/sh

picom -b &
pgrep -x sxhkd > /dev/null || sxhkd &
bash $HOME/.config/polybar/launch.sh

bspc monitor -d "^_^" "'_'" "*_*" "-_-"
feh --bg-scale /home/carrot/.config/bspwm/wallpaper 
xbindkeys -p

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color '#00'
bspc config border_width 3
